### ISSUE TITLE
Differences in results on OSX and Linux for

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mapnik-vector-tile#107]
Travis tests on linux are currently failing after calling `boost::geometry::correct` on the multipolygon data used in the `vector tile from simplified geojson` test. For some reason this triggered differences in the test result across osx and linux.

This issue is to track getting to the bottom of this failure. @flippmoke and I will dump ideas as comments.

**Comment by springmeyer** [comment]
I think we should try to narrow the test failure down first by removing the JSON parsing. Today I ran mapnik-vt and mapnik through `clang -fsanitize=address` and hit https://github.com/mapnik/mapnik/issues/2846 which is being triggered only by `build_geojson_ds` which is only used in this single failing test. So, we should try to rule out that issue as a cause.

**Comment by flippmoke** [comment]
@springmeyer we can easily narrow that down by adding a to WKT to the failing unit test.

**Comment by flippmoke** [comment]
@springmeyer After lots and lots of digging I found the reason for this. It is directly related the use of `std::sort` rather then `std::stable_sort` in the clipper. This was fixed in https://github.com/mapnik/mapnik/commit/775fcb53784b0a1cf73b3d5fea2f1b650947e068 and the tests have been updated in https://github.com/mapbox/mapnik-vector-tile/commit/a818ae6181279fbe2f11641af6afa866ba5db429

**Comment by springmeyer** [comment]
> It is directly related the use of std::sort rather then std::stable_sort in the clipper

Wow, interesting. Do you think this should be provided upstream to clipper?
