### ISSUE TITLE
Broken reprojection of layer extent when source != mercator

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mapnik-vector-tile#122]
This ticket is to track another regression in v0.8.x (after the move to using `boost::geometry::transform`) and therefore this is another followup to #111/#116 and #120.

What I'm seeing is that [the conversion of the buffered bbox to integer coordinates may throw](https://github.com/mapbox/mapnik-vector-tile/blob/ed89e3c557bb6b4838ceaf7e1ab4fbf39a74e98c/src/vector_tile_processor.ipp#L1242-L1243). When fixing #116 I noticed this might throw but could not think of a case where the buffered bbox would be outside the range of proj4 enough to trigger a throw. That was naive as I've now found that is highly probable when dealing with source data in a different projection than mercator.

Next steps:

  - How did this work before (in mapnik-vt `v0.7.1`)?
  - Should we be clipping the buffered box / `buffered_query_ext` to the layer extent / `layer_ext2` (and if so, how?)
  - testcase (can use the `NZ_Coastline_NZMG.shp` from https://github.com/mapbox/mapbox-studio/issues/1390)
  - what can we learn from https://github.com/mapbox/node-wmshp/pull/9

**Comment by BergWerkGIS** [comment]
FYI: 
Minimal test case with data from https://github.com/mapbox/mapbox-studio/issues/1390
https://github.com/BergWerkGIS/mapnik-proj4-crashes

**Comment by BergWerkGIS** [comment]
I stepped thru the New Zealand test case.

I think the problem is due to the fact, that local projections (NZMG in this case) are not always valid for the whole extent of the Web Mercator projection (±20037508/±20037508).

Taking [`NZGD2000 / New Zealand Transverse Mercator 2000`](http://spatialreference.org/ref/epsg/2193/) as an example, the valid bounds are within this small area and are likely to not be projectable to WebMercator.
![image](https://cloud.githubusercontent.com/assets/4549888/8288548/31d669ae-1917-11e5-998c-822e96aff202.png)


So the problem is the essentially same as in above referenced https://github.com/mapbox/node-wmshp/pull/9.

In `vector_tile_impl::backend_pbf` `extent` is defined as `WebMercator ±20037508/±20037508`.
Which fails to properly project to NZMG `buffered_query_ext`: `-5.19594e+24` / `-3.1224129e+24`.

![image](https://cloud.githubusercontent.com/assets/4549888/8288494/cb18cd7e-1916-11e5-9d55-bf7bff2407d9.png)



### Brainstorming solutions:

#### clip to layer extent

Probably the easiest solution (as already outlined by @springmeyer above) would be to clip with `layer_ext/layer_ext2` as this should have a high probability to be reasonably within the valid bounds of the local projection.
It has gone through some other software before and if weren't any problems, we shouldn't have any, too, right? 
Although it would have to be verified that the bounds, that are valid for the local projection, are also valid for WebMercator (remember, full WGS84 bounds are not valid for WebMercator).

#### define a valid Web Mercator extent for every projection available with proj4

This would probably be a nightmare to implement and maintain, but could be automated by either

* scraping http://spatialreference.org/
* scraping http://www.epsg-registry.org/ 
* querying the information from the Microsoft Access Database available at http://www.epsg.org/DownloadDataset
* writing a script that 
  * walks through all projections supported by proj4
  * performs projection of full bbox from Web Mercator to each local projection and back
  * compares, if the result is within a reasonable deviation from the original WebM bbox.
  * if yes, stores that information
  * if no, varies the size of the bbox till results match. Probably starting at `origin latitude`/`central meridan` and then expanding.

Although distortion of the bbox would also have to be considered (see images https://github.com/mapbox/node-wmshp/pull/9#issuecomment-92816770).

**Comment by BergWerkGIS** [comment]
^^ I used latest `mapnik/master` and `node-mapnik/master` as of today.

**Comment by springmeyer** [comment]
@BergWerkGIS - awesome research. My findings are the same. I'd love for `define a valid Web Mercator extent for every projection available with proj4` to be feasible but that is not an easy lift as far as I can tell. So I've been looking into `clip to layer extent`. It solves the immediate problem but for this testcase leads to lost of data at the edges of the geometry (once converted to mercator projection). This is going to be touch to solve elegantly so I'm planning on researching 1) clipping before reprojecting (this is what we did previously), or 2) buffering the layer extent clipping slightly (worry it will still result in bounds going outside the valid layer projection extents)

**Comment by BergWerkGIS** [comment]
> 1) clipping before reprojecting (this is what we did previously)

I'm not sure, I understand.
Do you say:

* Web Mercator tile extent was projected to local projection
* then source was clipped with projected tile extent in local projection
* then clipped source was projected to Web Mercator?

> 2) buffering the layer extent clipping slightly (worry it will still result in bounds going outside the valid layer projection extents)

Well, I think there is still enough room for buffering, because we are talking two extremes here.

1) trying to project whole world Web Mercator bbox into local projection (e.g. intended use for area of NZ only) might not work, because mathematically just not possible

![image](https://cloud.githubusercontent.com/assets/4549888/8317322/d9f4d4e6-19fc-11e5-801f-7bd4b8a539a5.png)

2) but creating a reasonable buffer around the extent of the source layer should still leave plenty of room. Just because the intended, optimal area for a certain local projection is relatively small, doesn't mean it is mathematically impossible to cover a much larger area with it.

e.g. Austria's [MGI/Austria GK M31](http://www.spatialreference.org/ref/epsg/31259/) is only intended to be used covering a small area in the east.
But that doesn't mean data, that lies even west of Switzerland, cannot be projected to that coordinate system.
Mathematically it is possible.

![image](https://cloud.githubusercontent.com/assets/4549888/8317203/15790466-19fc-11e5-9220-42122fef9b47.png)

**Comment by BergWerkGIS** [comment]
First finds, using `epsg` file that comes with proj4 and lower left point of full WebMerc bbox:

* `epsg` contains 4169 proj ini strings
* 5 fail to even initialize
* 1532 fail to transform from WebMerc to other
* from those 2632 left, 1532 fail to transform back to WebMerc within a tolerance of <20m for one or both values of the point

https://github.com/BergWerkGIS/bbox-finder

**Comment by springmeyer** [comment]
> Web Mercator tile extent was projected to local projection
> then source was clipped with projected tile extent in local projection
> then clipped source was projected to Web Mercator?

Yes, this is what was dodging this error before.

**Comment by springmeyer** [comment]
Will look at this with fresh eyes tomorrow - bbox-finder <-- wow looks handy!

**Comment by BergWerkGIS** [comment]
I did a bit more of research:
https://gist.github.com/BergWerkGIS/097aa7e8137f90329c1c

Interesting that the number of failed transformations (WebM->other) for each vertex of the bbox always have the same number of failures/successes.
But the affected EPSG codes are different, e.g:
https://gist.github.com/BergWerkGIS/097aa7e8137f90329c1c#file-trans-failed-ul-txt
vs
https://gist.github.com/BergWerkGIS/097aa7e8137f90329c1c#file-trans-failed-ur-txt

**Comment by BergWerkGIS** [comment]
I have a new suspect: `setlocale`

STACK TRACE:
![image](https://cloud.githubusercontent.com/assets/4549888/8376448/b41a4280-1c07-11e5-8b91-47998f18ef5d.png)


Source of proj4, where `setlocale` is called and the old locale is saved:
![image](https://cloud.githubusercontent.com/assets/4549888/8376457/cdec0f86-1c07-11e5-86c5-e704ad4bd68e.png)

According to [MSDN: setlocale](https://msdn.microsoft.com/en-us/library/x99tb11d.aspx)
<pre>
You can copy the string returned by setlocale to restore that part of the program's
 locale information.
Global or thread local storage is used for the string returned by setlocale.
<b>Later calls to setlocale overwrite the string, which invalidates string pointers 
returned by earlier calls.</b>
</pre>

**Maybe there is a lock needed around `setlocale` and `old_locale`?**

I tried to set `_configthreadlocale(_ENABLE_PER_THREAD_LOCALE)` in the init functions of `node.exe` and `node-mapnik`, but that didn't help.

[MSDN: `_configthreadlocale`](https://msdn.microsoft.com/en-us/library/26c0tb7x.aspx)
[MSDN: `Multithreading and Locales`](https://msdn.microsoft.com/en-us/library/ms235302.aspx)

**Comment by springmeyer** [comment]
@BergWerkGIS - yes, that is the likely culprit. Can you try removing those three lines completely (the strdup, strcmp, and setlocale calls) and see if the crash goes away?

**Comment by springmeyer** [comment]
@BergWerkGIS - let's track the windows crash at #127. This issue will be fixed shortly by #128

**Comment by springmeyer** [comment]
This is now solved. Walked through the code yesterday with @flippmoke and found that the failing transformation was actually a transformation that was unneeded. The failed transformation was a merc bbox that had been forward to the layer projection and failed when being backwarded back to mercator. Turns out we clip in psuedo-mercator (mercator coords scaled to integer screen coords) so the failing transform could be avoided by just using the original mercator bbox.

Now fixed by #128. Followup needed is fixing the windows crash uncovered by this testcase (but likely has been present for a long time and was unrelated to the regression this ticket captures): -> https://github.com/mapbox/mapnik-vector-tile/issues/127
