### ISSUE TITLE
'std::vector<ClipperLib::IntPoint,std::allocator<_Ty>>' to 'mapnik::geometry::linear_ring<T> &&

### ISSUE THREAD

**Issue by BergWerkGIS** [mapbox/mapnik-vector-tile#137]
I tried to build NETMapnik today (https://github.com/jbrwn/NET-Mapnik/issues/20#issuecomment-125561422), but got stuck with this error (using mapnik/master and mapnik-vector-tile/master as of today):

```
Error C2664

'void mapnik::geometry::polygon<T>::set_exterior_ring(mapnik::geometry::linear_ring<T> &&)': 
cannot convert argument 1 from 'std::vector<ClipperLib::IntPoint,std::allocator<_Ty>>' to
'mapnik::geometry::linear_ring<T> &&'

mapnik-vector-tile\src\vector_tile_processor.ipp 850
```

https://github.com/mapbox/mapnik-vector-tile/blob/master/src/vector_tile_processor.ipp#L850

I've included `clipper.cpp|hpp` from http://www.angusj.com/delphi/clipper.php as noted next to the include (https://github.com/mapbox/mapnik-vector-tile/blob/master/src/vector_tile_processor.ipp#L30).

But that doesn't seem to be the right one.
Also tried the clipper files from `mapnik/clipper` and `node-mapnik`, to no avail.

I've also included the headers from `protozero` and `pbf_|common|read|write|.hpp` from node-mapnik.

Any hints, which are the right clipper files and on how to make this compile?

Related errors:
![image](https://cloud.githubusercontent.com/assets/4549888/8930141/906de8c2-352b-11e5-9065-8be6fbaf068c.png)

**Comment by springmeyer** [comment]
What is currently needed/expected is:

 - the `r493-mapnik` branch of https://github.com/mapnik/clipper
 - these defines: https://github.com/mapbox/mapnik-vector-tile/blob/master/gyp/build.gyp#L8-L12

I recognize this is very obtuse - so I'll ponder how to make it easier in the future. But for now this setup is intentional: the goals are to make it easy to pull in updated clipper revisions quickly / make them easy to test.
