### ISSUE TITLE
tileinfo.cpp example is broken

### ISSUE THREAD

**Issue by lincomatic** [mapbox/mapnik-vector-tile#235]
The Makefile for c++/examples/tileinfo refers to a file which doesn't exist - ../../src/vector_tile.pb.cc

**Comment by springmeyer** [comment]
The `vector_tile.pb.cc` is generated by calling out to `protoc`. If you hit a compile error due to `vector_tile.pb.cc` not being there it probably means that you need `protoc` installed. You can get `protoc` by installing the google libprotobuf library (https://github.com/google/protobuf). We generally use/test with version 2.6.1 of that library.

**Comment by mikrosk** [comment]
>  If you hit a compile error due to vector_tile.pb.cc not being there it probably means that you need protoc installed

@springmeyer Can you be more specific? There is no rule in the example's Makefile which would generate such file? Where / how should I run that `protoc` ?

**Comment by talaj** [comment]
@mikrosk Here is the rule: https://github.com/mapbox/mapnik-vector-tile/blob/51b29f260783fa224d3f62d726be1a650525da3f/gyp/build.gyp#L27

**Comment by mikrosk** [comment]
@talaj ah ok, so to try the example I have to build the library first. now as I think about it, it sounds pretty logical.
