### ISSUE TITLE
Building against latest Mapnik

### ISSUE THREAD

**Issue by talaj** [mapbox/mapnik-vector-tile#241]
I was trying to build mapnik-vector-tile against latest Mapnik and encountered some incompatibilities concerning `geometry.hpp`. I was also looking into `develop-master` branch and similar for something new, but found nothing.

My quick and dirty fixes are here:
https://github.com/mapycz/mapnik-vector-tile/commit/ec213cf682118e2ab1490a0a4741e91191f8930f

Is there some compatible version I overlooked?
If not, are my changes worth pull request if I refine them?

**Comment by flippmoke** [comment]
@talaj Currently we have not updated it to be used with mapnik `3.1.x` and are still on the `3.0.x` branches. The reasoning behind this is partially because this is primarily used in node-mapnik and it is not currently ready to be used with C++14. There is some history behind this, but this is a great start at a `3.1.x` compatible branch here.

**Comment by springmeyer** [comment]
@talaj - @artemp is working on this over in https://github.com/mapbox/mapnik-vector-tile/pull/254. Let's discuss there.
