### ISSUE TITLE
Fix invalid polygon geometries (intersecting & colinear segments)

### ISSUE THREAD

**Issue by mourner** [mapbox/mapnik-vector-tile#53]
Clipping and simplification of polygon geometries often makes the polygons non-simple (with intersecting & touching segments). This is hard to handle when trying to tesselate such polygons for rendering (both on native & JS). Native uses [Clipper](http://www.angusj.com/delphi/clipper.php) (specifically [SimplifyPolygon](http://www.angusj.com/delphi/clipper/documentation/Docs/Units/ClipperLib/Functions/SimplifyPolygon.htm) with [StrictlySimple](http://www.angusj.com/delphi/clipper/documentation/Docs/Units/ClipperLib/Classes/Clipper/Properties/StrictlySimple.htm)) to fix the geometries. It has a port for JS, but applying it there would take a lot of precious CPU time, so it would be great to fix those problems on the VT side, using Clipper there.

Intersecting edges after simplification:
![image](https://cloud.githubusercontent.com/assets/25395/3983446/0ca4f698-287f-11e4-97b4-a9b67f8a0531.png)

Degenerate edges after clipping:
![image](https://cloud.githubusercontent.com/assets/25395/3983425/e0e9486a-287e-11e4-9ce0-247f02e320f0.png)

cc @springmeyer @yhahn

**Comment by springmeyer** [comment]
Update here:

### degenerate edges

We have a plan to fix degenerate edges which is to move away from the agg clipper to a better clipping library (The AGG clipper [ leaves degenerate edges by design](https://github.com/mapnik/mapnik/blob/fc911792982771a1edd674a903e72e02cb932a47/deps/agg/include/agg_conv_clip_polygon.h#L16-L23)). Since we need to support complex/potentially non-simple and self-intersecting polygons we cannot use `boost::geometry::intersection`. The clipping algorithm we choose also needs needs to maintain ring order (per https://github.com/mapbox/mapnik-vector-tile/issues/59#issuecomment-90348026 and https://github.com/mapnik/mapnik/issues/2756). Therefore my sense of the best plan is to use the clipper library along with its custom [clipper.PolyTree structure](http://www.angusj.com/delphi/clipper/documentation/Docs/Units/ClipperLib/Classes/PolyTree/_Body.htm)

To mitigate the performance hit of this new clipper, the plan is to simplify before clipping. To simplify before clipping the plan is to use `boost::geometry::simplify` which is working in https://github.com/mapbox/mapnik-vector-tile/pull/94 but needs more of a robust framework to stand on which is being tracked at https://github.com/mapnik/mapnik/issues/2753
 
### invalid polygons

Polygons with degenerate/colinear eges or self-intersections before they arrive to Mapnik are going to be much harder to fix. My understand from talking with @mourner is that the latest [earcut](https://github.com/mapbox/earcut) library (that we are targeting) is able to handle a variety of self-intersections. But we can consider using clipper ` SimplifyPolygon with StrictlySimple`. Once https://github.com/mapnik/mapnik/issues/2753 is in place I'll be in a better place to test plugging in this type of geometry fixing to assess if it is viable (or too slow, not robust enough).

In the meantime anyone that has small testcases of invalid polygons you think should still be supported, please share them in the form of GeoJSON files.

**Comment by mourner** [comment]
Done with VT2
